name: test basic
description: 'somente o basico'

inputs:
  basic:
    description: faz algo
    required: false
  inter:
    description: faz algo melhor
    required: false

runs:
  using: 'composite'
  steps:
   -run: basic.sh
   shell: bash
